### ISSUE TITLE
Header does not show all the data

### ISSUE THREAD

**Issue by gauravagerwala** [Azure/pcs-remote-monitoring-webui#1232] opened 2019-03-05 23:04 UTC
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
After upgrading to 2.2.0 the header does not display correctly.

![image](https://user-images.githubusercontent.com/9166802/53843572-7eeb2880-3f68-11e9-8be4-504cf3073f1f.png)

# Expected behavior 
The header remains the same as the previous versions

**Comment by ppathan** [comment] 2019-03-05 23:22
Hi @gauravagerwala We have recently changed the design to follow what you are seeing. Will close this issue as by design.

**Closed by ppathan** 2019-03-05 23:22 UTC
