### ISSUE TITLE
Telemetry chart not displaying report per time period drop down value

### ISSUE THREAD

**Issue by gauravagerwala** [Azure/pcs-remote-monitoring-webui#1233] opened 2019-03-07 20:34 UTC
@isaac-dasan still the issue exists Webui displaying only last 20min data irrespective of the time interval dropdown.

_Originally posted by @nareshshenishetty in https://github.com/Azure/pcs-remote-monitoring-webui/issues/1229#issuecomment-470682042_

**Comment by isaac-dasan** [comment] 2019-03-08 17:25
@gauravagerwala did you "empty cache and reload" in your browser? I double checked and that this issue is fixed in latest release and master branch.

**Comment by isaac-dasan** [comment] 2019-03-08 17:34
Reopening to hear confirmation from @gauravagerwala .

**Comment by isaac-dasan** [comment] 2019-03-08 18:16
@gauravagerwala @nareshshenishetty. Thank you for reporting. I just noticed Telemetry chart. Previously, I was looking at the alarm counts and it seems to be updating fine after the recent bug fix. 

This issue seems to be there since last release i.e 2.1.3.

**Comment by isaac-dasan** [comment] 2019-03-08 23:42
This is by design and not a bug. We only show 15mins of data in the telemetry chart since longer timperiods will slow the page loading. Everything other than the telemetry chart in the dashboard will be loaded according to the timeperiod dropdown.

**Closed by isaac-dasan** 2019-03-08 23:42 UTC
