### ISSUE TITLE
Simulation can be turned off but then can't be turned on.

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#722] opened 2017-10-25 21:32 UTC
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
1. Go to settings, turn simulation off.
2. Verify devices go offline.  You can also ssh into the vm to see from docker logs <sim> -tail 500 -f that the simulation is stopped.
3. Go to UI settings, turn simulation on.
4. The simulator doesn't start simulating devices again.  As above you can also ssh into the vm to see from docker logs <sim> -tail 500 -f that the simulation is still stopped and didn't get turned back on.

![image](https://user-images.githubusercontent.com/5084013/32024375-2047fec4-b991-11e7-9eca-0b585bc97329.png)

**Comment by dluc** [comment] 2017-10-25 22:10
As discussed offline, the root cause seems to be the HTTP method used by the UI. The UI currently uses PUT, replacing the simulation details, i.e. wiping the number of devices. Changing the call to use PATCH should fix the problem.

**Comment by spryor** [comment] 2017-10-25 22:23
Fix checked in.

**Closed by spryor** 2017-10-25 22:23 UTC
Labels: MVP, P1, Triaged
