### ISSUE TITLE
Refreshing browser filters to first device group

### ISSUE THREAD

**Issue by isaac73** [Azure/pcs-remote-monitoring-webui#1132] opened 2018-10-16 18:28 UTC
# Type of issue 

- [ ] Bug
- [x] New feature
- [ ] Enhancement

# Steps to reproduce 

1. Create a new device group that alphabetically will show up before "All devices".
2. Refresh the browser when anywhere in the RM solution.
3. Device group will automatically be filtered the first device group in the Device Group drop down.

# Expected behavior 
Refreshing should bring me to back to the device group that I was looking at before refreshing, or if not, "all devices".

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by mechaffin** [comment] 2018-10-25 17:54
Remember that the 'All Devices' group can be renamed. Its not a special group... its just one without a condition. There's no restriction that says other groups can't be created without a condition. 

Refresh should pick the first one in the list, period. There shouldn't be special logic to pick something else further down the list. Therefore, I believe the current behavior is correct.

**Comment by isaac73** [comment] 2018-10-26 23:07
@spryor should we make current deviceGroup value part of query string ? that way even if the browser is refreshed the device group is not changed.

**Comment by asdonald** [comment] 2018-10-31 18:42
@isaac73 Closed by design

**Comment by isaac73** [comment] 2018-10-31 21:11
Generally, If we select a device group (say `Trucks`) and refresh the browser, the resulting page should land me with the same device group (`Trucks`). It shouldn't be `All deviecs` nor the device group which is alphabetically first.

**Comment by asdonald** [comment] 2018-11-07 17:43
@asdonald  to move it to user voice.

**Comment by asdonald** [comment] 2019-01-03 19:12
Moved to user voice: https://feedback.azure.com/forums/916438-azure-iot-solution-accelerators/suggestions/36439924-refreshing-browser-should-not-default-to-first-dev

**Closed by asdonald** 2019-01-03 19:12 UTC
Labels: P3, Triaged, bug
