### ISSUE TITLE
Last Trigger field shows - Not Auto Refreshing 

### ISSUE THREAD

**Issue by asdonald** [Azure/pcs-remote-monitoring-webui#1161] opened 2018-11-08 22:23 UTC
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Title: Last Trigger field shows --- after editing the rule, value doesn't show until manual refresh
Repro:

select existing rule that has been triggered
edit rule
in grid view, last trigger field will show ---
manual refresh will show the value
Acceptance Criteria:

last trigger should show up after editing
OR the edit rule should treat the edited rule context as new such that you know the last triggered time for that rule with the new conditions because the new conditions have not yet been met 
...

**Comment by mechaffin** [comment] 2018-12-13 19:56
Regarding the maintenance page... The not auto refreshing issue would likely be fixed by the refactoring of the maintenance pages that UX talked with us about.  The issue is that right now only part of the page is refreshed when the "autorefresh" happens.  The very top part doesn't get updated and it has redundant data where that date is in the top not refreshed part as well as in the middle autorefreshed part.  With the UX redesign, my guess is that we'd reload the all of the data and the redundancy would be gone.

**Closed** 2019-01-15 18:02 UTC
Labels: P3, Triaged, enhancement, wontfix
